[environments]
default = { solve-group = "default" }
test = { features = ["test"], solve-group = "default" }

[project]
name = "odc-algo"
channels = ["conda-forge"]
platforms = ["linux-64", "osx-64", "osx-arm64"]

[tasks]
postinstall = "pip install --no-build-isolation --no-deps --disable-pip-version-check -e ."
build = "python -m build"
installhdstats = "pip install --prefer-binary -f https://packages.dea.ga.gov.au/hdstats/ hdstats"
test = { cmd = "pytest", depends_on = [ "postinstall", "installhdstats" ] }
testgm = { cmd = "pytest tests/test_geomedian.py", depends_on = [ "postinstall", "installhdstats" ] }

[dependencies]

python = ">=3.10"
python-build = ">0.10.0.*"
rust = "1.71.1.*"
