[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"

[tool.maturin]
#module-name = "odc-algo-backend.lib"
module-name = "odc.algo._backend"
# Build artifacts with the specified Cargo profile
profile = "release"

[project]
name = "odc-algo"
description = "Miscellaneous Algorithmic helper methods"
authors = [{name = "Open Data Cube"}]
maintainers = [{name = "Open Data Cube"}]
license = {text = "Apache License 2.0"}
requires-python = ">=3.8"
dependencies = [
    "affine",
    "dask",
    "dask-image",
    "datacube>=1.8.5",
    "distributed",
    "numexpr",
    "numpy",
    "rasterio>=1.3.2",
    "scikit-image",
    "toolz",
    "xarray",
]
dynamic = ["version"]

[project.readme]
file = "README.md"
content-type = "text/markdown"

[project.urls]
Homepage = "https://github.com/opendatacube/odc-tools/"

[project.optional-dependencies]
s3 = [
    "boto3",
    "odc-cloud",
]
test = ["pytest", "pytest-datadir"]

[tool.pixi.dependencies]

python = ">=3.10"
python-build = ">0.10.0.*"
rust = "1.71.1.*"

[tool.pixi.project]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tool.pixi.pypi-dependencies]
odc-algo = { path = ".", editable = true }

[tool.pixi.environments]
default = { solve-group = "default" }
s3 = { features = ["s3"], solve-group = "default" }
test = { features = ["test"], solve-group = "default" }

[tool.pixi.tasks]
postinstall = "pip install --no-build-isolation --no-deps --disable-pip-version-check -e ."
build = "python -m build"
installhdstats = "pip install --prefer-binary -f https://packages.dea.ga.gov.au/hdstats/ hdstats"
test = { cmd = "pytest", depends_on = [ "postinstall", "installhdstats" ] }
testgm = { cmd = "pytest tests/test_geomedian.py", depends_on = [ "postinstall", "installhdstats" ] }
